version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - npm install yarn
  build:
    commands:
      - docker build -t nest-rest-mongo .
  post_build:
    commands:
      - docker tag nest-rest-mongo:latest 800050217711.dkr.ecr.ap-northeast-2.amazonaws.com/nest-rest-mongo:latest
      - docker push 800050217711.dkr.ecr.ap-northeast-2.amazonaws.com/nest-rest-mongo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"nest-rest-mongo-container","imageUri":"%s"}]' 800050217711.dkr.ecr.ap-northeast-2.amazonaws.com/nest-rest-mongo:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
